version: '2'
services:
  bof: 
   build: ./bof/
   volumes:
    - ./bof/share:/home/bof:ro
    - ./bof/xinetd:/etc/xinetd.d/bof:ro
   ports:
    - "10000:4597"
  orw: 
   build: ./orw/
   volumes:
    - ./orw/share:/home/orw:ro
    - ./orw/xinetd:/etc/xinetd.d/orw:ro
   ports:
    - "10001:4597"
  leaked-flag: 
   build: ./leaked-flag/
   volumes:
    - ./leaked-flag/share:/home/leaked-flag:ro
    - ./leaked-flag/xinetd:/etc/xinetd.d/leaked-flag:ro
   ports:
    - "6666:4597"
  ppap: 
   build: ./ppap/
   volumes:
    - ./ppap/share:/home/ppap:ro
    - ./ppap/xinetd:/etc/xinetd.d/ppap:ro
   ports:
    - "10002:4597"
  hello: 
   build: ./hello/
   volumes:
    - ./hello/share:/home/hello:ro
    - ./hello/xinetd:/etc/xinetd.d/hello:ro
   ports:
    - "10003:4597"
  shellcode-2019: 
   build: ./shellcode-2019/
   volumes:
    - ./shellcode-2019/share:/home/shellcode-2019:ro
    - ./shellcode-2019/xinetd:/etc/xinetd.d/shellcode-2019:ro
   ports:
    - "10004:4597"
  secure-bof: 
   build: ./secure-bof/
   volumes:
    - ./secure-bof/share:/home/secure-bof:ro
    - ./secure-bof/xinetd:/etc/xinetd.d/secure-bof:ro
   ports:
    - "10005:4597"
  box: 
   build: ./box/
   volumes:
    - ./box/share:/home/box:ro
    - ./box/xinetd:/etc/xinetd.d/box:ro
   ports:
    - "10006:4597"
  box++: 
   build: ./box++/
   volumes:
    - ./box++/share:/home/box++:ro
    - ./box++/xinetd:/etc/xinetd.d/box++:ro
   ports:
    - "10007:4597"